/**
 * GENERATED by scripts/bake-routes.mjs — do not hand-edit.
 * The alfama walk's legs on real pedestrian ways from OpenStreetMap
 * foot-way data (Overpass pull, Dijkstra with road classes cost-penalized,
 * Douglas-Peucker simplified to ~3.5 m). Legs with no mapped ways (sand,
 * private yards) are hand-read waypoints instead. Coordinates are
 * [lat, lng]. Re-bake with the script if a stop moves.
 */

/** start->stairs — 252 m. */
export const START_TO_STAIRS: Array<[number, number]> = [
  [38.709900, -9.129660],
  [38.709897, -9.129599],
  [38.710080, -9.129851],
  [38.710475, -9.129593],
  [38.710479, -9.129510],
  [38.710734, -9.129244],
  [38.710985, -9.128811],
  [38.711320, -9.129039],
  [38.711560, -9.129310],
];

/** stairs->terrace — 207 m. */
export const STAIRS_TO_TERRACE: Array<[number, number]> = [
  [38.711560, -9.129310],
  [38.711660, -9.129278],
  [38.711723, -9.129408],
  [38.711776, -9.129391],
  [38.711604, -9.129573],
  [38.711511, -9.129597],
  [38.711599, -9.129909],
  [38.711494, -9.130062],
  [38.711545, -9.130289],
  [38.711473, -9.130363],
  [38.711464, -9.130535],
  [38.711630, -9.130501],
  [38.711616, -9.130400],
  [38.711740, -9.130220],
];

/** terrace->tram — 275 m. */
export const TERRACE_TO_TRAM: Array<[number, number]> = [
  [38.711740, -9.130220],
  [38.711779, -9.130484],
  [38.712111, -9.130239],
  [38.712501, -9.130621],
  [38.712732, -9.130550],
  [38.712751, -9.130601],
  [38.713054, -9.130572],
  [38.713234, -9.130407],
  [38.713284, -9.130248],
  [38.713060, -9.129740],
];

/** tram->end — 446 m. */
export const TRAM_TO_END: Array<[number, number]> = [
  [38.713060, -9.129740],
  [38.713284, -9.130248],
  [38.713827, -9.130432],
  [38.713951, -9.130537],
  [38.714075, -9.130219],
  [38.714286, -9.129978],
  [38.714419, -9.129702],
  [38.714816, -9.128682],
  [38.714889, -9.128707],
  [38.714907, -9.128614],
  [38.714806, -9.128627],
  [38.714562, -9.128509],
  [38.714619, -9.128147],
  [38.714600, -9.127700],
];
