/**
 * GENERATED by scripts/bake-routes.mjs — do not hand-edit.
 * The brooklyn walk's legs on real pedestrian ways from OpenStreetMap
 * foot-way data (Overpass pull, Dijkstra with road classes cost-penalized,
 * Douglas-Peucker simplified to ~3.5 m). Legs with no mapped ways (sand,
 * private yards) are hand-read waypoints instead. Coordinates are
 * [lat, lng]. Re-bake with the script if a stop moves.
 */

/** start->pier — 416 m. */
export const START_TO_PIER: Array<[number, number]> = [
  [40.697500, -73.998500],
  [40.697485, -73.998542],
  [40.698066, -73.998321],
  [40.698338, -73.997840],
  [40.698465, -73.997761],
  [40.698713, -73.997396],
  [40.699218, -73.997493],
  [40.699541, -73.997344],
  [40.699778, -73.998027],
  [40.699500, -73.998900],
];

/** pier->carousel — 931 m. */
export const PIER_TO_CAROUSEL: Array<[number, number]> = [
  [40.699500, -73.998900],
  [40.699778, -73.998027],
  [40.699541, -73.997344],
  [40.699746, -73.997041],
  [40.699934, -73.996960],
  [40.700055, -73.996726],
  [40.700001, -73.996381],
  [40.701876, -73.995488],
  [40.703030, -73.994793],
  [40.703021, -73.994406],
  [40.703420, -73.994001],
  [40.703558, -73.993990],
  [40.703961, -73.993371],
  [40.704001, -73.993077],
  [40.703950, -73.992543],
  [40.704080, -73.992221],
  [40.704301, -73.992232],
  [40.704430, -73.992380],
];

/** carousel->end — 260 m. */
export const CAROUSEL_TO_END: Array<[number, number]> = [
  [40.704430, -73.992380],
  [40.704302, -73.992268],
  [40.704302, -73.992129],
  [40.704134, -73.991976],
  [40.703969, -73.991665],
  [40.703912, -73.990703],
  [40.704135, -73.990567],
  [40.704268, -73.990322],
  [40.704177, -73.990169],
  [40.704153, -73.989931],
  [40.704100, -73.989900],
];
