/**
 * GENERATED by scripts/bake-routes.mjs — do not hand-edit.
 * The highline walk's legs on real pedestrian ways from OpenStreetMap
 * foot-way data (Overpass pull, Dijkstra with road classes cost-penalized,
 * Douglas-Peucker simplified to ~3.5 m). Legs with no mapped ways (sand,
 * private yards) are hand-read waypoints instead. Coordinates are
 * [lat, lng]. Re-bake with the script if a stop moves.
 */

/** start->overlook — 646 m. */
export const START_TO_OVERLOOK: Array<[number, number]> = [
  [40.739410, -74.008110],
  [40.739469, -74.007944],
  [40.739473, -74.006572],
  [40.742332, -74.004535],
  [40.742829, -74.005700],
  [40.742450, -74.005750],
];

/** overlook->lawn — 584 m. */
export const OVERLOOK_TO_LAWN: Array<[number, number]> = [
  [40.742450, -74.005750],
  [40.742829, -74.005700],
  [40.743323, -74.006887],
  [40.743761, -74.006901],
  [40.743937, -74.006768],
  [40.743983, -74.006868],
  [40.743951, -74.006736],
  [40.746299, -74.005033],
  [40.746000, -74.004800],
];

/** lawn->spur — 942 m. */
export const LAWN_TO_SPUR: Array<[number, number]> = [
  [40.746000, -74.004800],
  [40.746299, -74.005033],
  [40.752686, -74.000377],
  [40.752821, -74.000614],
  [40.752902, -74.000554],
  [40.753350, -74.000950],
];

/** spur->end — 434 m. */
export const SPUR_TO_END: Array<[number, number]> = [
  [40.753350, -74.000950],
  [40.752902, -74.000554],
  [40.753923, -73.999807],
  [40.754498, -74.001187],
  [40.754447, -74.001229],
  [40.754431, -74.001471],
  [40.754340, -74.001750],
  [40.754000, -74.002300],
];
