/**
 * GENERATED by scripts/bake-routes.mjs — do not hand-edit.
 * The lionshead walk's legs on real pedestrian ways from OpenStreetMap
 * foot-way data (Overpass pull, Dijkstra with road classes cost-penalized,
 * Douglas-Peucker simplified to ~3.5 m). Legs with no mapped ways (sand,
 * private yards) are hand-read waypoints instead. Coordinates are
 * [lat, lng]. Re-bake with the script if a stop moves.
 */

/** start->contour — 527 m. */
export const START_TO_CONTOUR: Array<[number, number]> = [
  [-33.936910, 18.394900],
  [-33.937532, 18.394515],
  [-33.938826, 18.393182],
  [-33.939326, 18.392916],
  [-33.939489, 18.392756],
  [-33.939652, 18.392157],
  [-33.939942, 18.391837],
  [-33.939975, 18.391737],
  [-33.939970, 18.391618],
  [-33.939837, 18.391330],
  [-33.939670, 18.391170],
];

/** contour->chains — 641 m. */
export const CONTOUR_TO_CHAINS: Array<[number, number]> = [
  [-33.939670, 18.391170],
  [-33.939470, 18.390905],
  [-33.939400, 18.390647],
  [-33.939269, 18.390615],
  [-33.938965, 18.391244],
  [-33.938553, 18.391333],
  [-33.938008, 18.391298],
  [-33.938263, 18.390817],
  [-33.937403, 18.390874],
  [-33.937321, 18.390787],
  [-33.937156, 18.390819],
  [-33.937122, 18.390709],
  [-33.936997, 18.390645],
  [-33.936877, 18.390673],
  [-33.936489, 18.390586],
  [-33.936412, 18.390485],
  [-33.935917, 18.390615],
  [-33.935967, 18.390501],
  [-33.935957, 18.390299],
  [-33.936187, 18.390170],
  [-33.936150, 18.390200],
];

/** chains->summit — 229 m. */
export const CHAINS_TO_SUMMIT: Array<[number, number]> = [
  [-33.936150, 18.390200],
  [-33.936191, 18.390013],
  [-33.936303, 18.389957],
  [-33.936343, 18.389830],
  [-33.936445, 18.389794],
  [-33.935403, 18.389266],
  [-33.935352, 18.389134],
  [-33.935040, 18.389140],
];

/** summit->end — 55 m. */
export const SUMMIT_TO_END: Array<[number, number]> = [
  [-33.935040, 18.389140],
  [-33.935352, 18.389134],
  [-33.935200, 18.389000],
];
