/**
 * GENERATED by scripts/bake-routes.mjs — do not hand-edit.
 * The reynisfjara walk's legs on real pedestrian ways from OpenStreetMap
 * foot-way data (Overpass pull, Dijkstra with road classes cost-penalized,
 * Douglas-Peucker simplified to ~3.5 m). Legs with no mapped ways (sand,
 * private yards) are hand-read waypoints instead. Coordinates are
 * [lat, lng]. Re-bake with the script if a stop moves.
 */

/** start->columns — 328 m. */
export const START_TO_COLUMNS: Array<[number, number]> = [
  [63.404330, -19.045230],
  [63.404050, -19.044800],
  [63.403750, -19.044300],
  [63.403450, -19.043500],
  [63.403200, -19.042600],
  [63.403000, -19.041700],
  [63.402850, -19.040900],
  [63.402630, -19.039990],
];

/** columns->waterline — 159 m. */
export const COLUMNS_TO_WATERLINE: Array<[number, number]> = [
  [63.402630, -19.039990],
  [63.402800, -19.040900],
  [63.402950, -19.041700],
  [63.403100, -19.042200],
  [63.403300, -19.042800],
];

/** waterline->end — 169 m. */
export const WATERLINE_TO_END: Array<[number, number]> = [
  [63.403300, -19.042800],
  [63.403500, -19.043500],
  [63.403750, -19.044200],
  [63.404000, -19.044600],
  [63.404180, -19.044800],
  [63.404330, -19.045230],
];
