/**
 * GENERATED by scripts/bake-routes.mjs — do not hand-edit.
 * The summerhacks walk's legs on real pedestrian ways from OpenStreetMap
 * foot-way data (Overpass pull, Dijkstra with road classes cost-penalized,
 * Douglas-Peucker simplified to ~3.5 m). Legs with no mapped ways (sand,
 * private yards) are hand-read waypoints instead. Coordinates are
 * [lat, lng]. Re-bake with the script if a stop moves.
 */

/** start->courtyard — 51 m. */
export const START_TO_COURTYARD: Array<[number, number]> = [
  [43.640580, -79.401900],
  [43.640660, -79.402080],
  [43.640710, -79.402060],
  [43.640790, -79.402280],
  [43.640850, -79.402350],
];

/** courtyard->buildRoom — 36 m. */
export const COURTYARD_TO_BUILD_ROOM: Array<[number, number]> = [
  [43.640850, -79.402350],
  [43.640940, -79.402210],
  [43.641010, -79.402260],
  [43.641100, -79.402180],
];

/** buildRoom->demo — 43 m. */
export const BUILD_ROOM_TO_DEMO: Array<[number, number]> = [
  [43.641100, -79.402180],
  [43.641180, -79.402360],
  [43.641260, -79.402330],
  [43.641310, -79.402470],
  [43.641350, -79.402480],
];

/** demo->end — 15 m. */
export const DEMO_TO_END: Array<[number, number]> = [
  [43.641350, -79.402480],
  [43.641390, -79.402380],
  [43.641420, -79.402320],
];
